#!/usr/bin/env bash
# Configures a custom http response header
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
str1="server_name _;\n\n\t error_page 404 \/404_error.html;\nlocation = \/404_error.html {\n\troot \/var\/www\/html;\ninternal;}\n"
str2="add_header X-Served-By \$hostname;\n"
str3="location \/redirect_me {\n\treturn 301 https://github.com/JDorangetree;}"
sed -i "s/server_name _;/$str1$str2$str3/" /etc/nginx/sites-enabled/default
service nginx start
