#!/usr/bin/env bash
# Configures a custom a new server
sudo apt-get update -y
sudo apt-get install nginx -y
new_string="server_name _;\n\trewrite ^\/redirect_me https://github.com/JDorangetree;"
nstr1="\n\tadd_header X-Served-By \$hostname;"
nstr2="\n\terror_page 404 \/404_error.html;\n\tlocation = \/404_error.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$new_string$nstr1$nstr2/" /etc/nginx/sites-available/default
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404_error.html
service nginx start
