#!/usr/bin/env bash
# Web Stack Debugging 1
sudo rm /etc/nginx/sites-enabled/default | ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
