#!/usr/bin/env bash
#Bash script that displays: To infinity and beyond
trap to_print 15
to_print()
{
    echo "I am invincible!!!";
}
while((1));
do
    echo "To infinity and beyond"
    sleep 2;
done
